# Generated by Django 5.1.7 on 2025-03-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_appuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
